extends Node

enum HEAD_TYPE {
	NONE,
	AILED, AILED_BLUSH,
	BLUSH_CLENCH, BLUSH_CLENCH_CLOSED,
	CLIMAX_COOLDOWN_0, CLIMAX_COOLDOWN_1, CLIMAX_COOLDOWN_2, CLIMAX_COOLDOWN_3, 
	CONCERNED,
	GRAPPLE_SURPRISE,
	HAPPY,
	HEAVY_BLUSH_CLENCH,
	HOOD,
	MOAN, MOAN_GREEN,
	PLEASURE_LOOKING_DOWN_1, PLEASURE_LOOKING_DOWN_2,
	SKINTIGHT,
	STUN_BUILDUP, STUN_MAX,
	SURPRISE,
}

enum EARING_TYPE { 
	NONE, HEND_WOVEN,
}

enum HEAD_EQUIP_TYPE {
	None,
	CHARGER_HELMET,
	GARD_CROWN,
	HOLLOW_GOOP,
	LATEX_HOOD, LATEX_MUZZLE,
	LEATHER_BIND, LEATHER_BIND_NO_GLOW,
	MAKESHIFT,
	OLD_BINDS_STAGE_2, OLD_BINDS_STAGE_3,
	PIERCE_BAR, PIERCE_RINGS,
	POACHER_NARG_HELM, POACHER_NARG_HELM_SET,
	RESTRAINT_RUBBER,
	SNAKE
}

enum BODY_TYPE {
	NONE, GRAPPLE, IDLE_FLUSH, NO_HANDS, RESTRAIN, STUN,
}

enum BODY_COVER_TYPE {
	NONE, GOOP, HOLLOW_GOOP, LATEX, POACHER_UNDERSUITE, POACHER_UNDERSUITE_BASE, SLIME
}

enum BODY_ARMS_TYPE {
	NONE,
	CHITIN,
	HAND_WOVEN,
	LATEX_ARMS, LATEX_ARMS_SNAKE, LATEX_BANDS,
	LEATHER_GLOVE_BINDS,
	MAKESHIFT,
	OLD_BINDS,
	RESTRAINT_RUBBER, RESTRAINT_RUBBER_DISENCHANT,
	SNAKE,
	TINKERER_ARM_BINDS,
}

enum BODY_UNDER_TYPE {
	NONE,
	HANDMADE,
	MAKESHIFT,
	RESTRAINT_RUBBER_1, RESTRAINT_RUBBER_2, RESTRAINT_RUBBER_2_DISENCHANT,
	SCRAPPY,
	SNAKE,
	TRAVEL,
}

enum BODY_LEGS_TYPE {
	NONE,
	HAND_WOVEN,
	LATEX_BANDS, LATEX_LEGGINGS, LATEX_LEGGINGS_SNAKE,
	MAKESHIFT,
	OLD_BINDS_STAGE1, OLD_BINDS_STAGE2,
	POACHER_LOIN,
	RESTRAINT_RUBBER,
	SNAKE,
	TINKERER_LEG_BINDS,
	TRAVEL,
}

enum BODY_NECKFUR_TYPE {
	BASE, FLAT, GOOP, GOOP_HARDEN, HOLLOWGOOP, LATEX_BULGE, SHIFTED, SLIME
}

enum BODY_NECK_TYPE {
	NONE, BLACK_COLLAR, NECKLACE_SPITTER, POACHER_COLLAR, POACHER_COLLAR_DISENCHANT, RESTRAINT_RUBBER, TOOTH_NECKLACE,
}

enum BODY_BALL_TYPE {
	NONE,
	BASE,
	ENLARGED1, ENLARGED2, ENLARGED3,
	GOOP_HARDEN,
	HOLLOW_GOOP,
	LATEX,
	POUCH_HUNTER
}

enum BODY_COCK_TYPE {
	# shared
	NONE,
	BASE1, BASE2,
	GOOP,
	GOOP_HARDEN,
	LATEX,
	POACH_HUNTER,
	
	# erect only
	SLIME,
}

enum TAIL_TYPE {
	BASE, HOLLOW_GOOP, LATEX,
}

enum TAIL_POUCH_TYPE {
	NONE, POUCH_1, POUCH_2, POUCH_TRAVEL,
}
