extends Node

enum HEAD_TYPE {
	NONE,
	AILED, AILED_BLUSH,
	BLUSH_CLENCH, BLUSH_CLENCH_CLOSED,
	CLIMAX_COOLDOWN_0, CLIMAX_COOLDOWN_1, CLIMAX_COOLDOWN_2, CLIMAX_COOLDOWN_3, 
	CONCERNED,
	GRAPPLE_SURPRISE,
	HAPPY,
	HEAVY_BLUSH_CLENCH,
	HOOD,
	MOAN, MOAN_GREEN,
	PLEASURE_LOOKING_DOWN_1, PLEASURE_LOOKING_DOWN_2,
	SKINTIGHT,
	STUN_BUILDUP, STUN_MAX,
	SURPRISE,
}

enum EARING_TYPE { 
	NONE, HEND_WOVEN,
}

enum BODY_TYPE {
	NONE, GRAPPLE, IDLE_FLUSH, NO_HANDS, RESTRAIN, STUN,
}

enum TAIL_TYPE {
	BASE, HOLLOW_GOOP, LATEX,
}

enum TAIL_POUCH_TYPE {
	NONE, POUCH_1, POUCH_2, POUCH_TRAVEL,
}
